"""add address to orders

Revision ID: 1934c52da16d
Revises: f8c9d0e1f2a3
Create Date: 2026-07-31 12:52:25.422161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1934c52da16d'
down_revision: Union[str, Sequence[str], None] = 'f8c9d0e1f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_orders_address_id_addresses',
        'orders',
        'addresses',
        ['address_id'],
        ['id'],
    )
    op.execute(
        """
        UPDATE orders AS order_row
        SET address_id = address.id
        FROM addresses AS address
        WHERE address.user_id = order_row.user_id
          AND address.is_default IS TRUE
          AND order_row.address_id IS NULL
        """
    )
    unassigned_orders = op.get_bind().execute(
        sa.text('SELECT count(*) FROM orders WHERE address_id IS NULL')
    ).scalar_one()
    if unassigned_orders:
        raise RuntimeError(
            'Every existing order must have a default address before this migration.'
        )
    op.alter_column('orders', 'address_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_address_id_addresses', 'orders', type_='foreignkey')
    op.drop_column('orders', 'address_id')
    # ### end Alembic commands ###
