"""add inventory fields to products

Revision ID: 330fb5b167a3
Revises: 301d234e3bbe
Create Date: 2026-07-29 10:37:32.815474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330fb5b167a3'
down_revision: Union[str, Sequence[str], None] = '301d234e3bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "products",
    sa.Column(
        "stock_quantity",
        sa.Integer(),
        nullable=False,
        server_default="0",
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_quantity')
    # ### end Alembic commands ###
