"""add unique constraint to user phone number

Revision ID: a685cd025258
Revises: 6e0310a3b219
Create Date: 2026-08-07 17:28:39.464939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a685cd025258'
down_revision: Union[str, Sequence[str], None] = '6e0310a3b219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=10),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'phone_number',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
