from enum import Enum


class ErrorCode(str, Enum):
    VALIDATION_ERROR = "VALIDATION_ERROR"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_TOKEN = "INVALID_TOKEN"
    ACCESS_DENIED = "ACCESS_DENIED"

    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"

    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
    CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS"
    CATEGORY_INACTIVE = "CATEGORY_INACTIVE"

    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    PRODUCT_ALREADY_EXISTS = "PRODUCT_ALREADY_EXISTS"

    INVALID_PRICE_RANGE = "INVALID_PRICE_RANGE"

    INVALID_SORT_FIELD = "INVALID_SORT_FIELD"

    INVALID_PAGE = "INVALID_PAGE"

    INVALID_PAGE_SIZE = "INVALID_PAGE_SIZE"

    PRODUCT_INACTIVE = "PRODUCT_INACTIVE"
    INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"
